# Generated by Django 3.0.6 on 2020-05-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='decription',
            new_name='text',
        ),
    ]
